version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: aitu_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
    depends_on:
      - backend
    networks:
      - aitu-network

  backend:
    build: ./backend
    container_name: aitu_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - aitu-network

  db:
    image: postgres:15
    container_name: aitu_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - aitu-network

  redis:
    image: redis:7-alpine
    container_name: aitu_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aitu-network

  nginx:
    image: nginx:alpine
    container_name: aitu_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/certs
    depends_on:
      - frontend
      - backend
    networks:
      - aitu-network

  celery:
    build: ./backend
    container_name: aitu_celery
    command: celery -A main.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - aitu-network

  telegram-bot:
    build: ./backend
    container_name: aitu_telegram_bot
    command: python bot/main.py
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://redis:6379
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - aitu-network

volumes:
  postgres_data:
  redis_data:

networks:
  aitu-network:
    driver: bridge